### ISSUE TITLE
[Bounty] Syncing Fix (Orphaned Blocks)

### ISSUE THREAD

**Issue by ghost** [WeyCoin/WeyWallet-Core#1]
Bounty: 60,000 WAE (4 masternodes)

Issue: The WeyWallet-Core needs to be adapted properly in order to work with the iOS wallet. So far, the syncing only detects orphaned blocks. If this can be fixed such that you can send, receive and fully sync without issues, the bounty will be paid.

**Comment by trappist** [comment]
Can you explain how to reproduce the bug and what to look for?

**Comment by ghost** [comment]
Please review the latest commit. So far I've discovered that the conversion from `int32_t` to `char*` doesn't work in C the same way it works in C++.

EDIT: Look in file `BRMerkleRoot.c` line `134`

EDIT2:

```
Expected Output (C++ Version):

versionCharArray: eb66d050 
nonceCharArray: eb66d058 ```

Output (C Version):

```Version Char Array: 27ab974 
Nonce Char Array: 27ab974 ```

EDIT3: The output isn't always the same, it's the size of the output that has to be the same

**Comment by ghost** [comment]
Fixed

**Comment by vvhof** [comment]
https://github.com/WeyCoin/WeyWallet-Core/commit/dc09ea45fc89d966d291d89f9a9ab5d9a63741fe
